language: go

os:
  - "linux"
  - "windows"
  - "osx"

go:
  - "1.13"
  - "1.14"
  - "1.15"


before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev ; fi

script:
  - go get -u github.com/pydio/cells-sync
  - go build main.go
  - go run main.go autotest
