files:
  - source: /app/ux/src/i18n/en.json
    translation: /app/ux/src/i18n/%locale%.json
    languages_mapping:
      locale:
        fr: fr
        de: de
        es-ES: es-es
        it: it
        lv: lv
        pt-BR: pt-br
        
