# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: workflow_dispatch
#  push:
#    branches: [ "webview-relaunch" ]
#  pull_request:
#    branches: [ "webview-relaunch" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: webview-relaunch

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
        
    - name: Setup Node
      uses: actions/setup-node@v2.5.2
      with:
        node-version: v16

    - name: Npm Install
      run: npm install
      working-directory: app/ux
      
    - name: NPM Build
      run: npm run build
      working-directory: app/ux
      
    - name: Build
      run: |
        $env:CGO_CXXFLAGS="-I${{github.workspace}}\libs\webview2\build\native\include"
        go build -ldflags "-H=windowsgui -X github.com/pydio/cells-sync/common.Version=0.9.5 -X github.com/pydio/cells-sync/common.BuildStamp=20230526 -X github.com/pydio/cells-sync/common.BuildRevision=rev" -o cells-sync.exe

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: cells-sync-windows
        path: cells-sync.exe
